// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Phoenix contributors
import type { PhoenixConfig } from "@phoenix/config";
import type { EventBus } from "@phoenix/event-bus";
import type { Logger } from "@phoenix/logging";
import type { PermissionGateway } from "@phoenix/permissions";
import type { EventStore, MeetingStore } from "@phoenix/persistence";
import type { StateEngine } from "@phoenix/state-engine";

/** Capability registry surface used by the API (implemented by @phoenix/capability-manager). */
export interface CapabilityService {
  list(): unknown[];
  get(id: string): unknown;
  enable(id: string): Promise<unknown>;
  disable(id: string): Promise<unknown>;
  configure(id: string, config: unknown): unknown;
  setSecret(id: string, name: string, value: string): Promise<unknown>;
  deleteSecret(id: string, name: string): Promise<unknown>;
  uninstall(id: string, options: { retainData?: boolean }): Promise<void>;
  invoke(id: string, command: string, input: unknown, actor?: string): unknown;
  operation(id: string): unknown;
  registerExternal(
    manifest: unknown,
    endpoint: string,
    callbackSecret?: string,
  ): Promise<{ capability: unknown; token: string }>;
  ingest(
    id: string,
    token: string | undefined,
    event: unknown,
  ): { ok: true; event: { event_id: string }; seq: number | null } | { ok: false; error: Error };
}

/** Notification surface used by the API (implemented by @phoenix/notifications). */
export interface NotificationsService {
  list(options: { unreadOnly?: boolean; limit?: number }): {
    notifications: unknown[];
    unread: number;
  };
  markRead(id: string): unknown;
  markAllRead(): number;
  preferences(): unknown;
  setPreferences(input: unknown): unknown;
}

/** One memory as the owner sees it. Never carries provenance internals or the dedupe key. */
export interface MemoryItemView {
  id: string;
  /** Capped at 2000 characters. */
  text: string;
  layer: string;
  domain: string;
  kind: "fact" | "interpretation";
  source: string;
  source_ref: string;
  scope: string;
  sensitivity: "public" | "internal" | "sensitive";
  observed_at: string;
  confidence: number;
  retention_days: number | null;
  expires_at: string | null;
  /** Secret-shaped text was removed before the memory was stored. */
  redacted: boolean;
}

export interface MemoryPageView {
  items: MemoryItemView[];
  total: number;
  counts: Record<string, number>;
  ai: { enabled: boolean };
}

export interface MemorySettingsView {
  retention_days: Record<"working" | "episodic" | "project" | "preference", number | null>;
  allow_sensitive_meetings: boolean;
  doc_paths: string[];
  capture_git: boolean;
}

export interface MemoryAnswerView {
  /** Stored facts only. Generated text is never in this list. */
  facts: {
    id: string;
    text: string;
    domain: string;
    source: string;
    source_ref: string;
    observed_at: string;
    sensitivity: "public" | "internal" | "sensitive";
  }[];
  /** Generated by a model from the facts above; null when no AI was used. */
  interpretation: string | null;
  processed_by: string | null;
  ai_used: boolean;
  note: string | null;
}

/**
 * Memory browsing and governance used by the API. The service decides what the caller may see
 * (the API never passes a viewer): every method applies the permission model itself.
 */
export interface MemoryApi {
  browse(query: { domain?: string; layer?: string; limit: number; offset: number }): MemoryPageView;
  search(query: { text: string; domain?: string; limit: number }): {
    items: (MemoryItemView & { score: number })[];
  };
  /** False when the id is unknown or not visible to the caller (the two are indistinguishable). */
  forget(id: string): boolean;
  /** Returns how many memories were deleted. `domain` absent = every visible memory. */
  deleteAll(domain?: string): number;
  settings(): MemorySettingsView;
  setSettings(input: unknown): Promise<MemorySettingsView>;
  ask(question: string): Promise<MemoryAnswerView>;
}

export interface AiStatusView {
  enabled: boolean;
  preferred: string | null;
  cloud_opt_in: { public: boolean; internal: boolean; sensitive: boolean };
  external_processing_granted: boolean;
  providers: {
    id: string;
    label: string;
    locality: "local" | "cloud";
    available: boolean;
    reason: string | null;
  }[];
}

/** AI settings, the external-processing grant and the cloud API key. Values are never returned. */
export interface AiApi {
  status(): Promise<AiStatusView>;
  setSettings(input: unknown): Promise<AiStatusView>;
  setExternalProcessing(granted: boolean): Promise<AiStatusView>;
  setSecret(value: string): Promise<void>;
  deleteSecret(): Promise<void>;
}

/** One task as listed. Stable snake_case JSON; the phase 31 doc is the contract. */
export interface AgentTaskSummaryView {
  id: string;
  kind: string;
  /** Latest run state: CREATED | READY | RUNNING | WAITING_APPROVAL | VERIFYING | COMPLETED | FAILED | CANCELLED. */
  state: string;
  title: string;
  requested_by: string;
  created_at: string;
  updated_at: string;
  failure_reason: string | null;
}

export interface AgentStepView {
  seq: number;
  kind: "stage" | "tool_call";
  name: string;
  status: string;
  /** Ids, counts and names only. */
  detail: Record<string, unknown>;
  /** Audit record of the policy decision (tool calls). */
  policy_audit_id: number | null;
  decision: string | null;
  risk: string | null;
  /** Audit record written for the step itself (`agent.stage.<name>`). */
  stage_audit_id: number | null;
  started_at: string;
  finished_at: string;
}

export interface AgentEvidenceView {
  id: string;
  kind: string;
  source: string;
  excerpt_hash: string;
  excerpt: string;
  truncated: boolean;
}

export interface AgentClaimView {
  text: string;
  evidence_ids: string[];
  grounded: boolean;
  origin: "rule" | "model";
  note: string | null;
}

export interface AgentProposalView {
  text: string;
  rationale: string;
  evidence_ids: string[];
  /** Always true in Phase 31: nothing executes a proposal. */
  advisory: true;
  grounded: boolean;
}

export interface AgentTaskDetailView {
  task: {
    id: string;
    kind: string;
    input: Record<string, unknown>;
    requested_by: string;
    created_at: string;
    correlation_id: string;
  };
  run: {
    id: string;
    state: string;
    agent_id: string;
    agent_version: string;
    created_at: string;
    updated_at: string;
    failure_reason: string | null;
  };
  steps: AgentStepView[];
  evidence: AgentEvidenceView[];
  summary: string | null;
  diagnosis: {
    summary: string;
    claims: AgentClaimView[];
    /** Grounded claims / claims, computed by Phoenix. */
    evidence_coverage: number;
    /** What the model said about its own confidence, if anything. Not a measure. */
    model_reported_confidence: string | null;
    ai_used: boolean;
  } | null;
  proposals: AgentProposalView[];
  ai_used: boolean;
  /** "Ollama · llama3.2 · on this device" when a model contributed. */
  processed_by: string | null;
  model_calls: number;
  verification: {
    passed: boolean;
    checks: { name: string; passed: boolean; detail: string; required: boolean }[];
  } | null;
  /** Every audit record this run wrote or caused (stage records and policy decisions). */
  audit_ids: number[];
}

export interface AgentSettingsView {
  enabled: boolean;
  kinds: string[];
  limits: {
    max_steps: number;
    max_tool_calls: number;
    max_wall_ms: number;
    max_active_runs: number;
  };
  active_runs: number;
}

/** What the confirmation prompt of a waiting agent run adds (all optional on the wire). */
export interface ConfirmationContextView {
  task_id: string;
  risk: string;
  target: string;
  preview: string;
  evidence_ids: string[];
}

/** Agent automation. Errors are PhoenixErrors; see the API contract in the phase 31 doc. */
export interface AgentApi {
  submit(request: { kind: unknown; input: unknown }): AgentTaskSummaryView;
  list(query: { state?: string; limit: number }): { tasks: AgentTaskSummaryView[] };
  get(id: string): AgentTaskDetailView | null;
  cancel(id: string): { cancelled: boolean; state: string } | null;
  settings(): AgentSettingsView;
  setSettings(input: unknown): AgentSettingsView;
  describeConfirmation(confirmationId: string): ConfirmationContextView | undefined;
}

/** Everything the API needs from Phoenix Core. */
export interface CoreServices {
  config: PhoenixConfig;
  logger: Logger;
  bus: EventBus;
  events: EventStore;
  state: StateEngine;
  permissions: PermissionGateway;
  capabilities?: CapabilityService;
  notifications?: NotificationsService;
  meetings?: MeetingStore;
  privacy?: {
    inventory(): unknown;
    retention(): unknown;
    setRetention(input: unknown): unknown;
    deleteAll(kind: unknown, confirm: unknown): unknown;
  };
  memory?: MemoryApi;
  ai?: AiApi;
  agents?: AgentApi;
  petSettings?(): unknown;
  setPetSettings?(input: unknown): unknown;
  /** Persists the user's sleep preference. */
  setSleeping(sleeping: boolean): void;
  health(): Record<string, unknown>;
  /** Support report with no secrets and no meeting content (GET /api/diagnostics). */
  diagnostics?(): unknown;
}
