// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Phoenix contributors
import type { PhoenixConfig } from "@phoenix/config";
import type { EventBus } from "@phoenix/event-bus";
import type { Logger } from "@phoenix/logging";
import type { PermissionGateway } from "@phoenix/permissions";
import type { EventStore, MeetingStore } from "@phoenix/persistence";
import type { StateEngine } from "@phoenix/state-engine";

/** Capability registry surface used by the API (implemented by @phoenix/capability-manager). */
export interface CapabilityService {
  list(): unknown[];
  get(id: string): unknown;
  enable(id: string): Promise<unknown>;
  disable(id: string): Promise<unknown>;
  configure(id: string, config: unknown): unknown;
  setSecret(id: string, name: string, value: string): Promise<unknown>;
  deleteSecret(id: string, name: string): Promise<unknown>;
  uninstall(id: string, options: { retainData?: boolean }): Promise<void>;
  invoke(id: string, command: string, input: unknown, actor?: string): unknown;
  operation(id: string): unknown;
  registerExternal(
    manifest: unknown,
    endpoint: string,
    callbackSecret?: string,
  ): Promise<{ capability: unknown; token: string }>;
  ingest(
    id: string,
    token: string | undefined,
    event: unknown,
  ): { ok: true; event: { event_id: string }; seq: number | null } | { ok: false; error: Error };
}

/** Notification surface used by the API (implemented by @phoenix/notifications). */
export interface NotificationsService {
  list(options: { unreadOnly?: boolean; limit?: number }): {
    notifications: unknown[];
    unread: number;
  };
  markRead(id: string): unknown;
  markAllRead(): number;
  preferences(): unknown;
  setPreferences(input: unknown): unknown;
}

/** One memory as the owner sees it. Never carries provenance internals or the dedupe key. */
export interface MemoryItemView {
  id: string;
  /** Capped at 2000 characters. */
  text: string;
  layer: string;
  domain: string;
  kind: "fact" | "interpretation";
  source: string;
  source_ref: string;
  scope: string;
  sensitivity: "public" | "internal" | "sensitive";
  observed_at: string;
  confidence: number;
  retention_days: number | null;
  expires_at: string | null;
  /** Secret-shaped text was removed before the memory was stored. */
  redacted: boolean;
}

export interface MemoryPageView {
  items: MemoryItemView[];
  total: number;
  counts: Record<string, number>;
  ai: { enabled: boolean };
}

export interface MemorySettingsView {
  retention_days: Record<"working" | "episodic" | "project" | "preference", number | null>;
  allow_sensitive_meetings: boolean;
  doc_paths: string[];
  capture_git: boolean;
}

export interface MemoryAnswerView {
  /** Stored facts only. Generated text is never in this list. */
  facts: {
    id: string;
    text: string;
    domain: string;
    source: string;
    source_ref: string;
    observed_at: string;
    sensitivity: "public" | "internal" | "sensitive";
  }[];
  /** Generated by a model from the facts above; null when no AI was used. */
  interpretation: string | null;
  processed_by: string | null;
  ai_used: boolean;
  note: string | null;
  retrieval: RetrievalInfoView;
}

/**
 * Memory browsing and governance used by the API. The service decides what the caller may see
 * (the API never passes a viewer): every method applies the permission model itself.
 */
export interface MemoryApi {
  browse(query: { domain?: string; layer?: string; limit: number; offset: number }): MemoryPageView;
  search(query: { text: string; domain?: string; limit: number }): Promise<{
    items: (MemoryItemView & { score: number })[];
    retrieval: RetrievalInfoView;
  }>;
  /** False when the id is unknown or not visible to the caller (the two are indistinguishable). */
  forget(id: string): boolean;
  /** Returns how many memories were deleted. `domain` absent = every visible memory. */
  deleteAll(domain?: string): number;
  settings(): MemorySettingsView;
  setSettings(input: unknown): Promise<MemorySettingsView>;
  ask(question: string): Promise<MemoryAnswerView>;
}

/** One reviewable decision, action item or other item taken from a meeting (Phase 35 contract). */
export interface MeetingItemView {
  id: string;
  meeting_id: string;
  kind: "decision" | "action_item" | "requirement" | "topic" | "project_ref";
  text: string;
  /** Action items only. */
  owner: string | null;
  due: string | null;
  status: "proposed" | "accepted" | "edited" | "rejected";
  /** "kage", "manual" or "ai:<provider>/<model>". */
  extracted_by: string;
  evidence: {
    source: "transcript" | "summary";
    quote: string;
    segment_start?: number;
    segment_end?: number;
    char_start?: number;
    char_end?: number;
  } | null;
  /** The wording before the first edit; null if never edited. */
  original: { text: string; owner: string | null; due: string | null } | null;
  created_at: string;
  reviewed_at: string | null;
  reviewed_by: string | null;
}

export interface MeetingItemListView {
  meeting_id: string;
  items: MeetingItemView[];
  /** Over ALL items of the meeting, ignoring the status and kind filters. */
  counts: Record<"proposed" | "accepted" | "edited" | "rejected", number>;
}

export interface MeetingReviewResultView {
  item: MeetingItemView;
  /** What the action did to memory: facts stored, and why memory refused an accepted item. */
  memory: { stored: number; refused: string[] };
}

export interface MeetingExtractionView {
  meeting_id: string;
  has_transcript: boolean;
  kage: { imported: number; duplicates: number; removed: number };
  /** null when the meeting has no transcript. */
  ai: {
    stored: number;
    /** Why no model was used, in words for the user; null when one was. */
    unavailable: string | null;
    stats: {
      chunks: number;
      chars_skipped: number;
      proposed: number;
      grounded: number;
      dropped: Record<
        "malformed" | "no_quote" | "quote_unusable" | "quote_not_found" | "text_not_supported",
        number
      >;
      owners_dropped: number;
      dues_dropped: number;
      ignored_fields: number;
      duplicates: number;
      capped: number;
      unparseable_chunks: number;
      failed_chunks: number;
    };
  } | null;
  counts: MeetingItemListView["counts"];
}

export interface MeetingHitView {
  meeting_id: string;
  /** The reviewed item behind the fact; null for facts from Kage's own summary. */
  item_id: string | null;
  memory_id: string;
  text: string;
  /** "reviewed": accepted in Phoenix. "kage": from Kage's summary, not reviewed here. */
  origin: "reviewed" | "kage";
  /** decision | action_item | summary ... */
  part: string;
  observed_at: string;
  freshness: "fresh" | "stale";
  score: number;
}

export interface MeetingSearchView {
  query: string;
  hits: MeetingHitView[];
  total: number;
  retrieval: RetrievalInfoView;
}

export interface MeetingAskView {
  question: string;
  /** Stored facts only, each with the meeting (and item) it came from. */
  facts: {
    ref: string;
    text: string;
    meeting_id: string;
    item_id: string | null;
    memory_id: string;
    origin: "reviewed" | "kage";
  }[];
  /** Generated from the facts above; null when no AI was used. */
  interpretation: string | null;
  processed_by: string | null;
  ai_used: boolean;
  note: string | null;
  retrieval: RetrievalInfoView;
}

/** How a search or ask found its facts (Phase 37). Additive on every retrieval response. */
export interface RetrievalInfoView {
  mode: "lexical" | "hybrid";
  /** Why the vector half was not used, when retrieval is enabled but fell back. */
  vector_skipped_reason?: string;
  /** The vector scan hit its cap and left the oldest memories out. */
  truncated?: boolean;
}

/** Review of meeting items, meeting search and questions. The service applies the viewer itself. */
export interface MeetingReviewApi {
  list(meetingId: string, filter: { status?: string; kind?: string }): MeetingItemListView;
  extract(meetingId: string): Promise<MeetingExtractionView>;
  add(
    meetingId: string,
    input: { kind: string; text: string; owner?: string | null; due?: string | null },
  ): MeetingReviewResultView;
  accept(itemId: string): MeetingReviewResultView;
  reject(itemId: string): MeetingReviewResultView;
  reopen(itemId: string): MeetingReviewResultView;
  edit(
    itemId: string,
    change: { text: string; owner?: string | null; due?: string | null },
  ): MeetingReviewResultView;
  search(query: string, limit: number): Promise<MeetingSearchView>;
  ask(question: string): Promise<MeetingAskView>;
}

export interface RetrievalSettingsView {
  /** Off by default. Needs AI to be on as well: with AI off nothing is embedded. */
  enabled: boolean;
  provider: string;
  model: string;
  /** Reciprocal-rank-fusion constant (1-200). Default 20. */
  k: number;
  /** Weight of the vector list against the keyword list (0-5). Default 0.5. */
  vector_weight: number;
  /** "feature" = deterministic reranker; "none". The model reranker is not offered. */
  reranker: "feature" | "none";
}

export interface RetrievalStatusView {
  enabled: boolean;
  /** True when search and ask use the vector index right now (enabled and AI on). */
  active: boolean;
  /** "retrieval_disabled" | "ai_disabled" when not active. */
  inactive_reason: string | null;
  provider: string;
  model: string;
  /** Vectors are only compared inside one space: `<provider>/<model>` (+ `#prefixed`). */
  vector_space: string;
  /** Memories with a vector in the active space / live memories in total. */
  embedded: number;
  total: number;
  unembedded: number;
  /** Memories whose embedding failed and is waiting to be retried. */
  failures: number;
  /** Vectors left from other embedding models (never used for search). */
  other_models: { model: string; vectors: number }[];
  payload_bytes: number;
  last_run: {
    at: string;
    embedded: number;
    failed: number;
    remaining: number;
    capped: boolean;
    degraded: string[];
  } | null;
}

export interface RetrievalApi {
  settings(): RetrievalSettingsView;
  setSettings(input: unknown): RetrievalSettingsView;
  status(): RetrievalStatusView;
}

export interface GraphProvenanceView {
  source_kind: "event" | "capability" | "memory" | "meeting" | "meeting_item" | "user";
  source_id: string;
  capability: string;
  observed_at: string;
  recorded_at: string;
  confidence: number;
  /** "rule" | "capability" | "user" | "ai:<model>". */
  asserted_by: string;
  scope: string;
  domain: string;
  sensitivity: "public" | "internal" | "sensitive";
  detail: Record<string, string | number | boolean | null>;
}

export interface GraphNodeView {
  /** `<Type>:<natural key>`, for example `Commit:owner/repo@<sha>`. */
  id: string;
  type: string;
  key: string;
  label: string;
  /** "proposed" only when every assertion is from a model. */
  status: "fact" | "proposed";
  detail: Record<string, string | number | boolean | null>;
  provenance: GraphProvenanceView[];
}

export interface GraphEdgeView {
  id: string;
  src: string;
  rel: string;
  dst: string;
  status: "fact" | "proposed";
  provenance: GraphProvenanceView[];
}

export interface GraphInspectionView {
  node: GraphNodeView;
  /** Newest observation first. */
  origin: GraphProvenanceView[];
  summary: { sources: number; assertors: string[]; capabilities: string[]; status: string };
  visible_edges: number;
}

export interface GraphNeighborhoodView {
  center: string;
  nodes: GraphNodeView[];
  edges: GraphEdgeView[];
  truncated: boolean;
}

export interface GraphPathView {
  nodes: GraphNodeView[];
  hops: { from: string; to: string; direction: "forward" | "backward"; edge: GraphEdgeView }[];
  /** One line per hop, built from graph facts only. */
  text: string;
}

export type GraphTruncationView = Partial<
  Record<"depth" | "fanout" | "visited" | "time" | "results", true>
>;

export type GraphAnswerView =
  | {
      kind: "why";
      subject: GraphNodeView | null;
      paths: GraphPathView[];
      truncated: GraphTruncationView;
    }
  | {
      kind: "which";
      subject: GraphNodeView | null;
      type: string;
      results: { node: GraphNodeView; path: GraphPathView }[];
      truncated: GraphTruncationView;
    }
  | {
      kind: "who";
      subject: GraphNodeView | null;
      people: { person: GraphNodeView; paths: GraphPathView[] }[];
      truncated: GraphTruncationView;
    };

export interface GraphAskView {
  question: string;
  /** Entities of the question that matched the graph exactly. Empty = no graph facts. */
  seeds: GraphNodeView[];
  /** Facts with their explanation paths. Never produced by a model. */
  answers: GraphAnswerView[];
  /** Memory text found for the same question (hybrid when retrieval is on), with citations. */
  documents: {
    id: string;
    text: string;
    source: string;
    source_ref: string;
    score: number | null;
  }[];
  notes: string[];
  retrieval: RetrievalInfoView;
  /** Present only when narration was requested and AI is on; the paths above are always returned. */
  narration: {
    text: string;
    /** False when the model's words were refused (it named something the path does not contain). */
    narrated: boolean;
    processed_by: string | null;
  } | null;
}

export interface GraphStatusView {
  /** Whole-graph row counts (not viewer-scoped). */
  nodes: number;
  edges: number;
  provenance: number;
  /** Nodes the viewer can see, by type. */
  visible_nodes_by_type: Record<string, number>;
  /** Commits backfilled from `git log` (author and files) since Core started. */
  commits_backfilled: number;
  last_ingest: { at: string; memories: number; meetings: number } | null;
}

export interface GraphApi {
  status(): GraphStatusView;
  inspect(nodeId: string): GraphInspectionView | null;
  neighbors(nodeId: string, depth: number): GraphNeighborhoodView | null;
  ask(question: string, options: { narrate: boolean }): Promise<GraphAskView>;
  /** Removes the person and everything only they supported, and keeps them out of the graph. */
  forgetPerson(name: string): { removed: { provenance: number; nodes: number; edges: number } };
}

export interface AiStatusView {
  enabled: boolean;
  preferred: string | null;
  cloud_opt_in: { public: boolean; internal: boolean; sensitive: boolean };
  external_processing_granted: boolean;
  providers: {
    id: string;
    label: string;
    locality: "local" | "cloud";
    available: boolean;
    reason: string | null;
  }[];
}

/** AI settings, the external-processing grant and the cloud API key. Values are never returned. */
export interface AiApi {
  status(): Promise<AiStatusView>;
  setSettings(input: unknown): Promise<AiStatusView>;
  setExternalProcessing(granted: boolean): Promise<AiStatusView>;
  setSecret(value: string): Promise<void>;
  deleteSecret(): Promise<void>;
}

/** One task as listed. Stable snake_case JSON; the phase 31 doc is the contract. */
export interface AgentTaskSummaryView {
  id: string;
  kind: string;
  /** Latest run state: CREATED | READY | RUNNING | WAITING_APPROVAL | VERIFYING | COMPLETED | FAILED | CANCELLED. */
  state: string;
  title: string;
  requested_by: string;
  created_at: string;
  updated_at: string;
  failure_reason: string | null;
}

export interface AgentStepView {
  seq: number;
  kind: "stage" | "tool_call";
  name: string;
  status: string;
  /** Ids, counts and names only. */
  detail: Record<string, unknown>;
  /** Audit record of the policy decision (tool calls). */
  policy_audit_id: number | null;
  decision: string | null;
  risk: string | null;
  /** Audit record written for the step itself (`agent.stage.<name>`). */
  stage_audit_id: number | null;
  started_at: string;
  finished_at: string;
}

export interface AgentEvidenceView {
  id: string;
  kind: string;
  source: string;
  excerpt_hash: string;
  excerpt: string;
  truncated: boolean;
}

export interface AgentClaimView {
  text: string;
  evidence_ids: string[];
  grounded: boolean;
  origin: "rule" | "model";
  note: string | null;
}

export interface AgentProposalView {
  text: string;
  rationale: string;
  evidence_ids: string[];
  /** Always true in Phase 31: nothing executes a proposal. */
  advisory: true;
  grounded: boolean;
}

export interface AgentTaskDetailView {
  task: {
    id: string;
    kind: string;
    input: Record<string, unknown>;
    requested_by: string;
    created_at: string;
    correlation_id: string;
  };
  run: {
    id: string;
    state: string;
    agent_id: string;
    agent_version: string;
    created_at: string;
    updated_at: string;
    failure_reason: string | null;
  };
  steps: AgentStepView[];
  evidence: AgentEvidenceView[];
  summary: string | null;
  diagnosis: {
    summary: string;
    claims: AgentClaimView[];
    /** Grounded claims / claims, computed by Phoenix. */
    evidence_coverage: number;
    /** What the model said about its own confidence, if anything. Not a measure. */
    model_reported_confidence: string | null;
    ai_used: boolean;
  } | null;
  proposals: AgentProposalView[];
  ai_used: boolean;
  /** "Ollama · llama3.2 · on this device" when a model contributed. */
  processed_by: string | null;
  model_calls: number;
  verification: {
    passed: boolean;
    checks: { name: string; passed: boolean; detail: string; required: boolean }[];
  } | null;
  /** Every audit record this run wrote or caused (stage records and policy decisions). */
  audit_ids: number[];
}

export interface AgentSettingsView {
  enabled: boolean;
  kinds: string[];
  limits: {
    max_steps: number;
    max_tool_calls: number;
    max_wall_ms: number;
    max_active_runs: number;
  };
  active_runs: number;
}

/** What the confirmation prompt of a waiting agent run adds (all optional on the wire). */
export interface ConfirmationContextView {
  task_id: string;
  risk: string;
  target: string;
  preview: string;
  evidence_ids: string[];
}

/**
 * The observation of one agent run: which model answered, which context and tools it used, what
 * the policy decided, how long each stage took and how it ended. Ids, names, counts, hashes and
 * numbers only: never a prompt, memory text, tool output or evidence text. A token count the model
 * service did not report is `"unknown"`, never an estimate.
 */
export interface AgentObservationView {
  version: 1;
  task_id: string;
  run_id: string;
  agent_id: string;
  agent_version: string;
  outcome: string;
  failure_reason: string | null;
  model: {
    provider: string;
    model: string;
    locality: "local" | "cloud";
    calls: number;
    input_tokens: number | "unknown";
    output_tokens: number | "unknown";
  } | null;
  /** SHA-256 of the agent's system prompt; null when Core does not know it. */
  prompt_version: string | null;
  /** SHA-256 over the sorted evidence ids and hashes. */
  context_version: string;
  /** Evidence by kind. */
  sources: Record<string, number>;
  memory_ids: string[];
  tool_calls: {
    tool: string;
    status: string;
    decision: string | null;
    risk: string | null;
    policy_audit_id: number | null;
    audit_confirmed: boolean;
  }[];
  permission_decisions: Record<string, number>;
  stages: { name: string; status: string; duration_ms: number; audit_id: number | null }[];
  total_duration_ms: number;
  tokens: { input: number | "unknown"; output: number | "unknown" };
  /** Micro-dollars. 0 for a local model, `"unknown"` for a cloud model (Core has no price table). */
  cost_micro_usd: number | "unknown";
  cloud_calls: number;
  ai_used: boolean;
  evidence_coverage: number | null;
  audit_ids: number[];
}

/** Agent automation. Errors are PhoenixErrors; see the API contract in the phase 31 doc. */
export interface AgentApi {
  submit(request: { kind: unknown; input: unknown }): AgentTaskSummaryView;
  list(query: { state?: string; limit: number }): { tasks: AgentTaskSummaryView[] };
  get(id: string): AgentTaskDetailView | null;
  cancel(id: string): { cancelled: boolean; state: string } | null;
  /** The harness observation of a task's run (Phase 33); null for an unknown task. */
  observation(id: string): AgentObservationView | null;
  settings(): AgentSettingsView;
  setSettings(input: unknown): AgentSettingsView;
  describeConfirmation(confirmationId: string): ConfirmationContextView | undefined;
}

export type PlanDestinationView =
  { system: "github"; repository: string } | { system: "frappe"; site: string };

export interface PlanStatementView {
  text: string;
  basis: "meeting" | "suggested" | "user";
  item_id?: string;
  quote?: string;
}

/** One engineering plan (Phase 36). `content_hash` is what `approve` must echo back. */
export interface PlanView {
  id: string;
  meeting_id: string;
  item_id: string;
  target: "github" | "frappe";
  destination: PlanDestinationView;
  status: "draft" | "proposed" | "approved" | "creating" | "created" | "failed" | "cancelled";
  content_hash: string;
  approved: { hash: string; by: string; at: string } | null;
  include_meeting_ref: boolean;
  title: string;
  generated_by: string;
  not_ai_generated: boolean;
  summary: PlanStatementView;
  acceptance_criteria: PlanStatementView[];
  risks: PlanStatementView[];
  open_questions: string[];
  tasks: {
    title: string;
    body: string;
    labels: string[];
    basis: "meeting" | "suggested" | "user";
    item_id?: string;
    quote?: string;
  }[];
  frappe: {
    doctype: string;
    fields: { label: string; fieldtype: string; required: boolean }[];
    workflow_states: string[];
    permissions: { role: string; read: boolean; write: boolean; create: boolean }[];
  } | null;
  source: {
    item_id: string;
    meeting_id: string;
    kind: string;
    item_text: string;
    owner: string | null;
    due: string | null;
    quote: string | null;
  };
  created_at: string;
  updated_at: string;
}

export interface PlanTaskRunView {
  task_index: number;
  idempotency_key: string;
  status: "pending" | "attempting" | "created" | "failed";
  attempts: number;
  external_id: string | null;
  url: string | null;
  error: string | null;
  updated_at: string;
}

export interface PlanLinkView {
  id: string;
  meeting_id: string;
  item_id: string;
  plan_id: string;
  task_index: number;
  system: "github" | "frappe";
  external_id: string;
  url: string;
  approved_by: string;
  approved_at: string;
  created_at: string;
}

export interface PlanDetailView {
  plan: PlanView;
  runs: PlanTaskRunView[];
  links: PlanLinkView[];
}

export interface PlanningStatusView {
  /** AI is on and at least one destination is configured. */
  enabled: boolean;
  ai_enabled: boolean;
  /** Sentences for the user when `enabled` is false. */
  reasons: string[];
  destinations: {
    github: { capability_enabled: boolean; write_token_set: boolean };
    frappe: { capability_enabled: boolean; write_token_set: boolean; sites: string[] };
  };
}

export interface PlanEditInput {
  title?: string;
  summary?: string;
  acceptance_criteria?: string[];
  tasks?: { title: string; body: string; labels?: string[] }[];
  risks?: string[];
  open_questions?: string[];
  destination?: PlanDestinationView;
}

/**
 * Plans from accepted meeting items and the creation of their tasks (Phase 36). Every method is the
 * signed-in user's own action; `approve` and `create` have no other caller than the session-token
 * routes (no tool, no capability command). Errors are PhoenixErrors.
 */
export interface PlanningApi {
  status(): PlanningStatusView;
  generate(
    itemId: string,
    destination: PlanDestinationView,
  ): Promise<{
    plan: PlanView;
    generation: {
      stats: {
        proposed: number;
        grounded: number;
        suggested: number;
        ignored_fields: number;
        design_dropped: number;
      };
      unavailable: string | null;
    };
  }>;
  listForMeeting(meetingId: string): {
    meeting_id: string;
    plans: {
      id: string;
      item_id: string;
      target: "github" | "frappe";
      status: PlanView["status"];
      title: string;
      task_count: number;
      created_at: string;
      updated_at: string;
    }[];
  };
  linksForMeeting(meetingId: string): { meeting_id: string; links: PlanLinkView[] };
  linksForTask(system: "github" | "frappe", externalId: string): { links: PlanLinkView[] };
  get(planId: string): PlanDetailView;
  preview(planId: string): {
    plan_id: string;
    tasks: {
      task_index: number;
      tool: string;
      input: Record<string, unknown>;
      decision: { effect: string; risk: string; reasons: string[]; matched: string[] };
    }[];
  };
  edit(planId: string, change: PlanEditInput): PlanDetailView;
  propose(planId: string): PlanDetailView;
  approve(planId: string, input: { hash: string; includeMeetingRef: boolean }): PlanDetailView;
  create(planId: string): Promise<{
    plan: PlanView;
    runs: PlanTaskRunView[];
    links: PlanLinkView[];
    failure: { task_index: number; message: string } | null;
  }>;
  cancel(planId: string): PlanDetailView;
}

export interface WorkflowView {
  id: string;
  name: string;
  enabled: boolean;
  environment: "local" | "dev" | "staging" | "production";
  version: number;
  hash: string;
  trigger: { event: string; where?: string };
  authorisation_reasons: string[];
  authorised: boolean;
  problems: string[];
}

export interface WorkflowAuthorisationView {
  id: string;
  workflow_id: string;
  definition_hash: string;
  authorised_by: string;
  authorised_at: string;
  expires_at: string | null;
  revoked_at: string | null;
  revoked_by: string | null;
  /** Not revoked, not expired and bound to the workflow's current hash. */
  live: boolean;
}

export interface WorkflowRunSummaryView {
  id: string;
  workflow_id: string;
  workflow_name: string;
  status: string;
  terminal: boolean;
  correlation_id: string;
  trigger_event_id: string;
  chain_depth: number;
  current_step: string | null;
  reason: string | null;
  created_at: string;
  started_at: string | null;
  finished_at: string | null;
}

export interface WorkflowRunView extends WorkflowRunSummaryView {
  trigger: string;
  steps: {
    seq: number;
    step_id: string;
    phase: "step" | "compensation";
    type: string;
    status: string;
    attempts: number;
    destructive: boolean;
    tool: string | null;
    input: string | null;
    output: string | null;
    error: string | null;
    started_at: string;
    finished_at: string | null;
  }[];
}

export interface WorkflowMetricsView {
  runs_started: number;
  runs_succeeded: number;
  runs_failed: number;
  runs_cancelled: number;
  runs_rejected: number;
  runs_interrupted: number;
  runs_refused: number;
  runs_compensated: number;
  runs_needing_attention: number;
  steps_succeeded: number;
  steps_failed: number;
  step_failure_rate: number;
  duration: { p50: number; p90: number; p99: number; samples: number } | null;
  approvals_waiting: number;
  approvals_approved: number;
  approvals_rejected: number;
  approvals_expired: number;
}

/**
 * Workflows (Phases 39-40). Every change is the signed-in user's own action (the runtime holds the
 * only `WorkflowAdmin`); nothing a tool, an agent or a workflow step can call reaches it. Errors are
 * PhoenixErrors; see the API contract in the phase 39 and 40 docs.
 */
export interface WorkflowsApi {
  list(): WorkflowView[];
  get(id: string): {
    workflow: WorkflowView;
    definition: unknown;
    authorisations: WorkflowAuthorisationView[];
    created_by: string | null;
    created_at: string | null;
    updated_by: string | null;
    updated_at: string | null;
  } | null;
  validate(definition: unknown): {
    valid: boolean;
    problems: string[];
    hash: string | null;
    authorisation: { required: boolean; reasons: string[] } | null;
  };
  save(definition: unknown): {
    created: boolean;
    workflow: WorkflowView;
    stored_enabled: boolean;
    authorisation_required: boolean;
    authorisation_reasons: string[];
  };
  setEnabled(id: string, enabled: boolean): WorkflowView;
  authorise(id: string, input: { hash: string; expiresAt?: string }): {
    authorisation: WorkflowAuthorisationView;
    workflow: WorkflowView;
  };
  revoke(id: string): { revoked: number; workflow: WorkflowView };
  start(id: string, payload: Record<string, unknown>): { run: WorkflowRunSummaryView };
  cancelRun(runId: string): { cancelled: true; status: string };
  listRuns(query: { workflowId?: string; status?: string; limit: number }): {
    runs: WorkflowRunSummaryView[];
  };
  getRun(runId: string): WorkflowRunView | null;
  metrics(): Record<string, WorkflowMetricsView>;
}

/** Everything the API needs from Phoenix Core. */
export interface CoreServices {
  config: PhoenixConfig;
  logger: Logger;
  bus: EventBus;
  events: EventStore;
  state: StateEngine;
  permissions: PermissionGateway;
  capabilities?: CapabilityService;
  notifications?: NotificationsService;
  meetings?: MeetingStore;
  privacy?: {
    inventory(): unknown;
    retention(): unknown;
    setRetention(input: unknown): unknown;
    deleteAll(kind: unknown, confirm: unknown): unknown;
  };
  memory?: MemoryApi;
  meetingReview?: MeetingReviewApi;
  retrieval?: RetrievalApi;
  graph?: GraphApi;
  ai?: AiApi;
  agents?: AgentApi;
  planning?: PlanningApi;
  workflows?: WorkflowsApi;
  petSettings?(): unknown;
  setPetSettings?(input: unknown): unknown;
  /** Persists the user's sleep preference. */
  setSleeping(sleeping: boolean): void;
  health(): Record<string, unknown>;
  /** Support report with no secrets and no meeting content (GET /api/diagnostics). */
  diagnostics?(): unknown;
}
