// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Phoenix contributors
import type { PhoenixConfig } from "@phoenix/config";
import type { EventBus } from "@phoenix/event-bus";
import type { Logger } from "@phoenix/logging";
import type { PermissionGateway } from "@phoenix/permissions";
import type { EventStore, MeetingStore } from "@phoenix/persistence";
import type { StateEngine } from "@phoenix/state-engine";

/** Capability registry surface used by the API (implemented by @phoenix/capability-manager). */
export interface CapabilityService {
  list(): unknown[];
  get(id: string): unknown;
  enable(id: string): Promise<unknown>;
  disable(id: string): Promise<unknown>;
  configure(id: string, config: unknown): unknown;
  setSecret(id: string, name: string, value: string): Promise<unknown>;
  deleteSecret(id: string, name: string): Promise<unknown>;
  uninstall(id: string, options: { retainData?: boolean }): Promise<void>;
  invoke(id: string, command: string, input: unknown, actor?: string): unknown;
  operation(id: string): unknown;
  registerExternal(
    manifest: unknown,
    endpoint: string,
    callbackSecret?: string,
  ): Promise<{ capability: unknown; token: string }>;
  ingest(
    id: string,
    token: string | undefined,
    event: unknown,
  ): { ok: true; event: { event_id: string }; seq: number | null } | { ok: false; error: Error };
}

/** Notification surface used by the API (implemented by @phoenix/notifications). */
export interface NotificationsService {
  list(options: { unreadOnly?: boolean; limit?: number }): {
    notifications: unknown[];
    unread: number;
  };
  markRead(id: string): unknown;
  markAllRead(): number;
  preferences(): unknown;
  setPreferences(input: unknown): unknown;
}

/** One memory as the owner sees it. Never carries provenance internals or the dedupe key. */
export interface MemoryItemView {
  id: string;
  /** Capped at 2000 characters. */
  text: string;
  layer: string;
  domain: string;
  kind: "fact" | "interpretation";
  source: string;
  source_ref: string;
  scope: string;
  sensitivity: "public" | "internal" | "sensitive";
  observed_at: string;
  confidence: number;
  retention_days: number | null;
  expires_at: string | null;
  /** Secret-shaped text was removed before the memory was stored. */
  redacted: boolean;
}

export interface MemoryPageView {
  items: MemoryItemView[];
  total: number;
  counts: Record<string, number>;
  ai: { enabled: boolean };
}

export interface MemorySettingsView {
  retention_days: Record<"working" | "episodic" | "project" | "preference", number | null>;
  allow_sensitive_meetings: boolean;
  doc_paths: string[];
  capture_git: boolean;
}

export interface MemoryAnswerView {
  /** Stored facts only. Generated text is never in this list. */
  facts: {
    id: string;
    text: string;
    domain: string;
    source: string;
    source_ref: string;
    observed_at: string;
    sensitivity: "public" | "internal" | "sensitive";
  }[];
  /** Generated by a model from the facts above; null when no AI was used. */
  interpretation: string | null;
  processed_by: string | null;
  ai_used: boolean;
  note: string | null;
}

/**
 * Memory browsing and governance used by the API. The service decides what the caller may see
 * (the API never passes a viewer): every method applies the permission model itself.
 */
export interface MemoryApi {
  browse(query: { domain?: string; layer?: string; limit: number; offset: number }): MemoryPageView;
  search(query: { text: string; domain?: string; limit: number }): {
    items: (MemoryItemView & { score: number })[];
  };
  /** False when the id is unknown or not visible to the caller (the two are indistinguishable). */
  forget(id: string): boolean;
  /** Returns how many memories were deleted. `domain` absent = every visible memory. */
  deleteAll(domain?: string): number;
  settings(): MemorySettingsView;
  setSettings(input: unknown): Promise<MemorySettingsView>;
  ask(question: string): Promise<MemoryAnswerView>;
}

export interface AiStatusView {
  enabled: boolean;
  preferred: string | null;
  cloud_opt_in: { public: boolean; internal: boolean; sensitive: boolean };
  external_processing_granted: boolean;
  providers: {
    id: string;
    label: string;
    locality: "local" | "cloud";
    available: boolean;
    reason: string | null;
  }[];
}

/** AI settings, the external-processing grant and the cloud API key. Values are never returned. */
export interface AiApi {
  status(): Promise<AiStatusView>;
  setSettings(input: unknown): Promise<AiStatusView>;
  setExternalProcessing(granted: boolean): Promise<AiStatusView>;
  setSecret(value: string): Promise<void>;
  deleteSecret(): Promise<void>;
}

/** Everything the API needs from Phoenix Core. */
export interface CoreServices {
  config: PhoenixConfig;
  logger: Logger;
  bus: EventBus;
  events: EventStore;
  state: StateEngine;
  permissions: PermissionGateway;
  capabilities?: CapabilityService;
  notifications?: NotificationsService;
  meetings?: MeetingStore;
  privacy?: {
    inventory(): unknown;
    retention(): unknown;
    setRetention(input: unknown): unknown;
    deleteAll(kind: unknown, confirm: unknown): unknown;
  };
  memory?: MemoryApi;
  ai?: AiApi;
  petSettings?(): unknown;
  setPetSettings?(input: unknown): unknown;
  /** Persists the user's sleep preference. */
  setSleeping(sleeping: boolean): void;
  health(): Record<string, unknown>;
  /** Support report with no secrets and no meeting content (GET /api/diagnostics). */
  diagnostics?(): unknown;
}
