// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Phoenix contributors
import { formatDate, safeHttpUrl } from "../core/format";
import type { MemoryAnswer, MemorySensitivity } from "../core/types";

export const SENSITIVITY_LABEL: Record<MemorySensitivity, string> = {
  public: "Public",
  internal: "Internal",
  sensitive: "Sensitive",
};

/** A source reference as text; a link only when it is a plain http(s) URL. Never HTML. */
export function SourceRef({ sourceRef }: { sourceRef: string | null }) {
  if (!sourceRef) return null;
  const href = safeHttpUrl(sourceRef);
  return (
    <>
      {" ("}
      {href ? (
        <a href={href} target="_blank" rel="noopener noreferrer">
          {sourceRef}
        </a>
      ) : (
        sourceRef
      )}
      {")"}
    </>
  );
}

/**
 * An answer from POST /api/memory/ask. Stored facts always come first, each with where it came
 * from; the interpretation is below them, labelled as generated (or "No AI was used"). Nothing
 * here is invented by the page: every label restates a field of the response.
 */
export function AnswerView({ answer }: { answer: MemoryAnswer }) {
  return (
    <div className="memory-answer">
      <h4>Stored facts</h4>
      {answer.facts.length === 0 ? (
        <p className="muted small">No stored facts matched your question.</p>
      ) : (
        <ul className="memory-facts">
          {answer.facts.map((f) => (
            <li key={f.id}>
              <p className="memory-text">{f.text}</p>
              <p className="muted small">
                {f.domain} · from {f.source}
                <SourceRef sourceRef={f.source_ref} /> ·{" "}
                <time dateTime={f.observed_at}>{formatDate(f.observed_at)}</time> ·{" "}
                {SENSITIVITY_LABEL[f.sensitivity]}
              </p>
            </li>
          ))}
        </ul>
      )}
      <h4>Interpretation</h4>
      {answer.ai_used && answer.interpretation ? (
        <div className="memory-interpretation">
          <p className="small">
            <strong>Generated by {answer.processed_by ?? "an AI model"}, not a stored fact.</strong>
          </p>
          <p className="memory-text">{answer.interpretation}</p>
        </div>
      ) : (
        <p className="small">
          {answer.ai_used ? "AI was used but gave no interpretation." : "No AI was used."}
        </p>
      )}
      {answer.note && <p className="muted small">{answer.note}</p>}
    </div>
  );
}
