// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Phoenix contributors
import type { PrivacyClass } from "@phoenix/ai-models";

/**
 * working = this session only; episodic = things that happened (a commit, a meeting);
 * project = knowledge about a project (docs); preference = how the user likes things done.
 */
export const MEMORY_LAYERS = ["working", "episodic", "project", "preference"] as const;
export type MemoryLayer = (typeof MEMORY_LAYERS)[number];

export const MEMORY_DOMAINS = ["git", "meeting", "project", "preference", "general"] as const;
export type MemoryDomain = (typeof MEMORY_DOMAINS)[number];

/**
 * `fact` is something a source reported and Phoenix stored as it was. `interpretation` was
 * generated by a model; it needs model + provider provenance and is never shown as a fact.
 */
export type MemoryKind = "fact" | "interpretation";

export type MemoryProvenance = Record<string, unknown>;

/** A stored memory. Every field is metadata the owner can inspect. */
export interface MemoryItem {
  id: string;
  /** Stable identity of the source fact. Capturing the same source twice is a no-op. */
  dedupeKey: string;
  /** Capability that produced it: "git", "kage", "project-docs". */
  source: string;
  /** What it came from inside the source: a meeting id, a file path, a commit. */
  sourceRef: string;
  owner: string;
  /** "repo:<name>", "meeting:<id>", "path:<absolute>", "global". */
  scope: string;
  layer: MemoryLayer;
  domain: MemoryDomain;
  kind: MemoryKind;
  /** Empty once the item is a tombstone. */
  text: string;
  createdAt: string;
  /** When the remembered thing happened (commit time, meeting start, file mtime). */
  observedAt: string;
  /** The last time the source still said this. Freshness is derived from it. */
  lastConfirmedAt: string;
  /** Days after `lastConfirmedAt` the item counts as stale. null = never goes stale. */
  freshnessTtlDays: number | null;
  sensitivity: PrivacyClass;
  /** Source event id, meeting id, commit sha, model + provider for interpretations. */
  provenance: MemoryProvenance;
  /** 0..1. How far the source can be trusted to have said this correctly. */
  confidence: number;
  retentionDays: number | null;
  expiresAt: string | null;
  /** Set when the item was deleted or expired. The text and provenance are gone. */
  deletedAt: string | null;
}

export type Freshness = "fresh" | "stale";

/** Derived, never stored: stale once `freshnessTtlDays` have passed since last confirmed. */
export function freshnessOf(
  item: Pick<MemoryItem, "lastConfirmedAt" | "freshnessTtlDays">,
  now: Date,
): Freshness {
  if (item.freshnessTtlDays === null) return "fresh";
  const staleAt = Date.parse(item.lastConfirmedAt) + item.freshnessTtlDays * 86_400_000;
  return now.getTime() >= staleAt ? "stale" : "fresh";
}

export function maxSensitivity(levels: readonly PrivacyClass[]): PrivacyClass {
  if (levels.includes("sensitive")) return "sensitive";
  if (levels.includes("internal")) return "internal";
  return "public";
}
