// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Phoenix contributors
// @vitest-environment happy-dom
import { act, cleanup, fireEvent, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { CHAT_MAX_CHARS } from "../src/core/chat-store";
import { safeHttpUrl } from "../src/core/format";
import type { MemoryAnswer } from "../src/core/types";
import { parseCiForm } from "../src/components/Chat";
import { FakeWebSocket } from "./fake-ws";
import {
  fawkesAvatar,
  mount,
  openPanel,
  openTab,
  petState,
  sendEvent,
  taskDetail,
  taskSummary,
  TASK_ID,
} from "./harness";

beforeEach(() => FakeWebSocket.reset());
afterEach(() => cleanup());

const fact = (patch = {}) => ({
  id: "m1",
  text: "Commit abc123 changed the router",
  domain: "git",
  source: "git",
  source_ref: "abc123",
  observed_at: "2026-10-01T10:00:00Z",
  sensitivity: "internal" as const,
  ...patch,
});

const answer = (patch: Partial<MemoryAnswer> = {}): MemoryAnswer => ({
  facts: [fact()],
  interpretation: null,
  processed_by: null,
  ai_used: false,
  note: null,
  ...patch,
});

function openChat(routes: Parameters<typeof mount>[0] = {}) {
  const m = mount(routes);
  openPanel();
  openTab("Chat");
  return m;
}

const box = () => screen.getByLabelText("Message to Fawkes") as HTMLTextAreaElement;
const type = (text: string) => fireEvent.change(box(), { target: { value: text } });
const send = () => fireEvent.click(screen.getByRole("button", { name: "Send" }));
const log = () => screen.getByRole("list", { name: "Conversation" });
/** The conversation's own messages (not the fact list items nested inside a reply). */
const messages = () => Array.from(log().querySelectorAll(":scope > li"));

describe("Chat: asking", () => {
  it("posts the question and shows your message, then Fawkes's reply, in that order", async () => {
    const { api } = openChat({ "POST /api/memory/ask": () => answer() });
    type("  what changed in the router?  ");
    send();
    await within(log()).findByText("Commit abc123 changed the router");
    expect(api.posts("/api/memory/ask")[0]?.body).toEqual({
      question: "what changed in the router?",
    });
    await waitFor(() => expect(messages()).toHaveLength(2));
    expect(messages()[0]?.textContent).toContain("You");
    expect(messages()[0]?.textContent).toContain("what changed in the router?");
    expect(messages()[1]?.textContent).toContain("Fawkes");
    expect(box().value).toBe("");
  });

  it("lists stored facts with source, date and sensitivity BEFORE the interpretation", async () => {
    openChat({
      "POST /api/memory/ask": () =>
        answer({
          interpretation: "The router change looks routine.",
          processed_by: "Ollama (this device) · llama3.2",
          ai_used: true,
        }),
    });
    type("router?");
    send();
    await waitFor(() => expect(messages()).toHaveLength(2));
    const reply = messages()[1] as HTMLElement;
    const text = reply.textContent ?? "";
    expect(text).toContain("git · from git (abc123)");
    expect(text).toContain("Internal");
    const factAt = text.indexOf("Commit abc123 changed the router");
    const labelAt = text.indexOf(
      "Generated by Ollama (this device) · llama3.2, not a stored fact.",
    );
    const interpAt = text.indexOf("The router change looks routine.");
    expect(factAt).toBeGreaterThan(-1);
    expect(labelAt).toBeGreaterThan(factAt);
    expect(interpAt).toBeGreaterThan(labelAt);
    expect(within(reply).queryByText("No AI was used.")).toBeNull();
  });

  it("says 'No AI was used' when the API says so, and never shows a generated label", async () => {
    openChat({ "POST /api/memory/ask": () => answer() });
    type("router?");
    send();
    expect(await screen.findByText("No AI was used.")).toBeTruthy();
    expect(screen.queryByText(/Generated by/)).toBeNull();
  });

  it("shows API-supplied notes, and an honest empty result", async () => {
    openChat({
      "POST /api/memory/ask": () => answer({ facts: [], note: "AI is off for this question." }),
    });
    type("anything");
    send();
    expect(await screen.findByText("No stored facts matched your question.")).toBeTruthy();
    expect(screen.getByText("AI is off for this question.")).toBeTruthy();
  });

  it("renders source references as text, linking only plain http(s) URLs", async () => {
    openChat({
      "POST /api/memory/ask": () =>
        answer({
          facts: [
            fact({ id: "a", text: "web fact", source_ref: "https://example.com/pr/1" }),
            fact({ id: "b", text: "script fact", source_ref: "javascript:alert(1)" }),
            fact({ id: "c", text: "html fact", source_ref: "<img src=x onerror=alert(1)>" }),
            fact({ id: "d", text: "creds fact", source_ref: "https://user:pw@example.com/" }),
          ],
        }),
    });
    type("links");
    send();
    await screen.findByText("web fact");
    const links = within(log()).getAllByRole("link");
    expect(links).toHaveLength(1);
    expect(links[0]?.getAttribute("href")).toBe("https://example.com/pr/1");
    expect(links[0]?.getAttribute("rel")).toBe("noopener noreferrer");
    expect(links[0]?.getAttribute("target")).toBe("_blank");
    // The hostile references are visible as plain text and created no element.
    expect(within(log()).getByText(/javascript:alert\(1\)/)).toBeTruthy();
    expect(within(log()).getByText(/<img src=x onerror=alert\(1\)>/)).toBeTruthy();
    expect(log().querySelector("img")).toBeNull();
  });

  it("shows an API error as an alert that says what failed, and keeps the conversation going", async () => {
    let fail = true;
    openChat({
      "POST /api/memory/ask": () =>
        fail
          ? new Response(JSON.stringify({ code: "INVALID_REQUEST", message: "Memory is locked" }), {
              status: 400,
            })
          : answer(),
    });
    type("first");
    send();
    const alert = await screen.findByRole("alert");
    expect(alert.textContent).toBe("Asking memory failed: Memory is locked.");
    fail = false;
    type("second");
    send();
    await screen.findByText("Commit abc123 changed the router");
    expect(messages()).toHaveLength(4);
  });

  it("says Core is unreachable when the request itself fails", async () => {
    openChat({
      "POST /api/memory/ask": () => {
        throw new TypeError("network down");
      },
    });
    type("hello");
    send();
    expect((await screen.findByRole("alert")).textContent).toBe(
      "Asking memory failed: Phoenix Core is unreachable.",
    );
  });
});

describe("Chat: composing", () => {
  it("sends on Enter and inserts no newline; Shift+Enter does not send", async () => {
    const { api } = openChat({ "POST /api/memory/ask": () => answer() });
    type("hello");
    fireEvent.keyDown(box(), { key: "Enter", shiftKey: true });
    expect(api.posts("/api/memory/ask")).toHaveLength(0);
    fireEvent.keyDown(box(), { key: "Enter" });
    await waitFor(() => expect(api.posts("/api/memory/ask")).toHaveLength(1));
  });

  it("does not send an empty or whitespace-only message", () => {
    const { api } = openChat();
    expect((screen.getByRole("button", { name: "Send" }) as HTMLButtonElement).disabled).toBe(true);
    type("   \n ");
    fireEvent.keyDown(box(), { key: "Enter" });
    expect(api.posts("/api/memory/ask")).toHaveLength(0);
  });

  it("caps a message at 500 characters, matching the API, and says how many are used", () => {
    const { api } = openChat();
    expect(box().maxLength).toBe(CHAT_MAX_CHARS);
    type("x".repeat(600));
    expect(box().value).toHaveLength(500);
    expect(screen.getByText(/500 \/ 500 characters/)).toBeTruthy();
    expect(api.posts("/api/memory/ask")).toHaveLength(0);
  });

  it("shows a busy state only while the request is in flight, and ignores a second send", async () => {
    const gate = Promise.withResolvers<void>();
    const { api } = openChat({
      "POST /api/memory/ask": async () => {
        await gate.promise;
        return answer();
      },
    });
    expect(screen.queryByText(/Waiting for Phoenix Core/)).toBeNull();
    type("first");
    send();
    expect(await screen.findByText(/Waiting for Phoenix Core to answer/)).toBeTruthy();
    expect((screen.getByRole("button", { name: "Sending…" }) as HTMLButtonElement).disabled).toBe(
      true,
    );
    type("second");
    fireEvent.keyDown(box(), { key: "Enter" });
    expect(api.posts("/api/memory/ask")).toHaveLength(1);
    gate.resolve();
    await screen.findByText("Commit abc123 changed the router");
    expect(screen.queryByText(/Waiting for Phoenix Core/)).toBeNull();
  });

  it("keeps the conversation when you switch tabs, in memory only", async () => {
    openChat({ "POST /api/memory/ask": () => answer() });
    type("remember me");
    send();
    await screen.findByText("Commit abc123 changed the router");
    openTab("Activity");
    openTab("Chat");
    expect(messages()).toHaveLength(2);
    expect(Object.keys(window.localStorage)).toEqual([]);
    expect(Object.keys(window.sessionStorage)).toEqual([]);
  });
});

describe("Chat: no fabricated state", () => {
  it("never says Fawkes is thinking unless Core's real state is THINKING", async () => {
    const { ws } = openChat({ "POST /api/memory/ask": () => answer() });
    act(() => ws.message("state.changed", petState("IDLE", "All quiet")));
    expect(screen.queryByText(/thinking/i)).toBeNull();
    type("hello");
    send();
    await screen.findByText("Commit abc123 changed the router");
    expect(screen.queryByText(/thinking/i)).toBeNull();
    expect(fawkesAvatar().getAttribute("data-state")).toBe("IDLE");

    act(() => ws.message("state.changed", petState("THINKING", "CI failure in acme/app")));
    expect(fawkesAvatar().getAttribute("data-state")).toBe("THINKING");
    expect(screen.getByText(/Fawkes is thinking\./)).toBeTruthy();
  });

  it("shows the avatar state Core reports while a request is in flight, not an invented one", async () => {
    const gate = Promise.withResolvers<void>();
    const { ws } = openChat({
      "POST /api/memory/ask": async () => {
        await gate.promise;
        return answer();
      },
    });
    act(() => ws.message("state.changed", petState("IDLE", "All quiet")));
    type("hello");
    send();
    await screen.findByText(/Waiting for Phoenix Core/);
    expect(fawkesAvatar().getAttribute("data-state")).toBe("IDLE");
    gate.resolve();
  });

  it("shows no confidence percentage for an answer", async () => {
    openChat({
      "POST /api/memory/ask": () =>
        answer({ interpretation: "Probably fine.", processed_by: "Ollama", ai_used: true }),
    });
    type("how sure?");
    send();
    await screen.findByText("Probably fine.");
    expect(log().textContent).not.toMatch(/\d\s?%/);
    expect(log().textContent).not.toMatch(/confiden/i);
  });
});

describe("Chat: LISTENING", () => {
  it("shows LISTENING while you are writing, and only then", async () => {
    const gate = Promise.withResolvers<void>();
    const { ws } = openChat({
      "POST /api/memory/ask": async () => {
        await gate.promise;
        return answer();
      },
    });
    act(() => ws.message("state.changed", petState("IDLE", "All quiet")));
    expect(fawkesAvatar().getAttribute("data-state")).toBe("IDLE");

    fireEvent.focus(box());
    expect(fawkesAvatar().getAttribute("data-state")).toBe("IDLE"); // focus without text
    type("hel");
    expect(fawkesAvatar().getAttribute("data-state")).toBe("LISTENING");

    send(); // request in flight: not listening, even if you start the next message meanwhile
    await screen.findByText(/Waiting for Phoenix Core/);
    expect(fawkesAvatar().getAttribute("data-state")).toBe("IDLE");
    type("next one");
    expect(fawkesAvatar().getAttribute("data-state")).toBe("IDLE");
    gate.resolve();
    await screen.findByText("Commit abc123 changed the router");
    expect(fawkesAvatar().getAttribute("data-state")).toBe("LISTENING"); // "next one" is still being written
    type("again");
    expect(fawkesAvatar().getAttribute("data-state")).toBe("LISTENING");
    fireEvent.blur(box());
    expect(fawkesAvatar().getAttribute("data-state")).toBe("IDLE");
  });

  it("never covers a real state: an error stays an error while you type", () => {
    const { ws } = openChat();
    act(() => ws.message("state.changed", petState("ERROR", "Build failed")));
    fireEvent.focus(box());
    type("hello");
    expect(fawkesAvatar().getAttribute("data-state")).toBe("ERROR");
  });

  it("is not stuck when the panel closes while you are typing", () => {
    const { ws } = openChat();
    act(() => ws.message("state.changed", petState("IDLE", "All quiet")));
    fireEvent.focus(box());
    type("hello");
    expect(fawkesAvatar().getAttribute("data-state")).toBe("LISTENING");
    fireEvent.click(screen.getByRole("button", { name: "Close Pet Panel" }));
    expect(fawkesAvatar().getAttribute("data-state")).toBe("IDLE");
  });
});

describe("Chat: Diagnose a CI failure", () => {
  const settings = (enabled: boolean) => ({
    enabled,
    kinds: ["ci_failure"],
    limits: { max_steps: 8, max_tool_calls: 12, max_wall_ms: 600000, max_active_runs: 4 },
    active_runs: 0,
  });
  const fillForm = (repo: string, run = "") => {
    fireEvent.click(screen.getByRole("button", { name: "Diagnose a CI failure" }));
    fireEvent.change(screen.getByLabelText("Repository (owner/name)"), { target: { value: repo } });
    if (run) fireEvent.change(screen.getByLabelText(/^Run id/), { target: { value: run } });
    fireEvent.click(screen.getByRole("button", { name: "Start diagnosis" }));
  };

  it("validates the form and sends nothing for bad input", () => {
    const { api } = openChat({ "GET /api/agent/settings": () => settings(true) });
    fillForm("not a repo");
    expect(screen.getByRole("alert").textContent).toContain('"owner/name"');
    fireEvent.change(screen.getByLabelText("Repository (owner/name)"), {
      target: { value: "acme/app" },
    });
    fireEvent.change(screen.getByLabelText(/^Run id/), { target: { value: "-4" } });
    fireEvent.click(screen.getByRole("button", { name: "Start diagnosis" }));
    expect(screen.getByRole("alert").textContent).toContain("positive whole number");
    expect(api.posts("/api/agent/tasks")).toHaveLength(0);
  });

  it("parses the form the way the API does", () => {
    expect(parseCiForm(" acme/app ", "")).toEqual({ repository: "acme/app" });
    expect(parseCiForm("acme/app", " 37145498780 ")).toEqual({
      repository: "acme/app",
      runId: 37145498780,
    });
    for (const bad of ["acme", "../x", "a/b/c", "acme/..", "-a/b", "a b/c", ""]) {
      expect(typeof parseCiForm(bad, ""), bad).toBe("string");
    }
    for (const run of ["0", "1.5", "1e3", "abc", "9".repeat(16)]) {
      expect(typeof parseCiForm("acme/app", run), run).toBe("string");
    }
  });

  it("starts the task and shows it inline, updating on live agent_run events", async () => {
    let state: "RUNNING" | "COMPLETED" = "RUNNING";
    const { api, ws } = openChat({
      "GET /api/agent/settings": () => settings(true),
      "POST /api/agent/tasks": () => ({ task: taskSummary("CREATED") }),
      [`GET /api/agent/tasks/${TASK_ID}`]: () =>
        taskDetail(state, state === "COMPLETED" ? { summary: "The lint step failed." } : {}),
    });
    fillForm("acme/app", "7");
    const task = await screen.findByRole("article", { name: "Agent task: CI failure in acme/app" });
    expect(api.posts("/api/agent/tasks")[0]?.body).toEqual({
      kind: "ci_failure",
      input: { repository: "acme/app", run_id: 7 },
    });
    expect(screen.queryByLabelText("Diagnose a CI failure")).toBeNull(); // form closed
    expect(messages()[0]?.textContent).toContain("Diagnose a CI failure in acme/app (run 7)");
    await within(task).findByText("Running");
    state = "COMPLETED";
    sendEvent(ws, 1, "agent_run.completed", { task_id: TASK_ID });
    await within(task).findByText("Finished");
    expect(within(task).getByText(/The lint step failed\./)).toBeTruthy();
    expect(within(task).queryByRole("button", { name: /Cancel task/ })).toBeNull();
  });

  it("omits run_id when empty (latest failed run)", async () => {
    const { api } = openChat({
      "GET /api/agent/settings": () => settings(true),
      "POST /api/agent/tasks": () => ({ task: taskSummary("CREATED") }),
      [`GET /api/agent/tasks/${TASK_ID}`]: () => taskDetail("RUNNING"),
    });
    fillForm("acme/app");
    await screen.findByRole("article", { name: /Agent task/ });
    expect(api.posts("/api/agent/tasks")[0]?.body).toEqual({
      kind: "ci_failure",
      input: { repository: "acme/app" },
    });
  });

  it("explains that automation is off, before and after trying", async () => {
    openChat({
      "GET /api/agent/settings": () => settings(false),
      "POST /api/agent/tasks": () =>
        new Response(
          JSON.stringify({
            code: "CAPABILITY_DISABLED",
            message: "Automation is off",
            details: ["AGENTS_DISABLED"],
          }),
          { status: 409 },
        ),
    });
    expect(await screen.findByText(/Automation is off, so Fawkes cannot start tasks/)).toBeTruthy();
    fillForm("acme/app");
    expect((await screen.findByRole("alert")).textContent).toContain("Automation is off");
    expect(screen.queryByRole("article")).toBeNull();
    expect(screen.queryByRole("list", { name: "Conversation" })).toBeNull(); // nothing was said
  });

  it("cancels a running task", async () => {
    let state: "RUNNING" | "CANCELLED" = "RUNNING";
    const { api, ws } = openChat({
      "GET /api/agent/settings": () => settings(true),
      "POST /api/agent/tasks": () => ({ task: taskSummary("CREATED") }),
      [`GET /api/agent/tasks/${TASK_ID}`]: () => taskDetail(state),
      [`POST /api/agent/tasks/${TASK_ID}/cancel`]: () => {
        state = "CANCELLED";
        return { cancelled: true, state: "CANCELLED" };
      },
    });
    fillForm("acme/app");
    fireEvent.click(
      await screen.findByRole("button", { name: "Cancel task: CI failure in acme/app" }),
    );
    await screen.findByText("The task was cancelled.");
    expect(api.posts(`/api/agent/tasks/${TASK_ID}/cancel`)).toHaveLength(1);
    sendEvent(ws, 2, "agent_run.cancelled", { task_id: TASK_ID });
    await screen.findByText("Cancelled");
    expect(screen.queryByRole("button", { name: /Cancel task/ })).toBeNull();
  });
});

describe("safeHttpUrl", () => {
  it("accepts plain http(s) and refuses everything else", () => {
    expect(safeHttpUrl("https://example.com/a?b=1")).toBe("https://example.com/a?b=1");
    expect(safeHttpUrl("http://127.0.0.1:4870/x")).toBe("http://127.0.0.1:4870/x");
    for (const bad of [
      null,
      "",
      "abc123",
      "/etc/passwd",
      "javascript:alert(1)",
      "JaVaScRiPt:alert(1)",
      "data:text/html,<b>",
      "file:///etc/passwd",
      "https://u:p@example.com/",
      "https://exa mple.com/",
      "https://example.com/\nx",
      `https://example.com/${"a".repeat(3000)}`,
    ]) {
      expect(safeHttpUrl(bad), String(bad)).toBeNull();
    }
  });
});
