// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Phoenix contributors
//
// Renders every Fawkes state from the shipped asset into preview SVGs:
//   docs/images/fawkes-states.svg        animated, as Fawkes moves
//   docs/images/fawkes-states-still.svg  reduced motion: the still pose per state
// Run after changing pet/assets:  npx tsx scripts/render-fawkes-gallery.ts
import { writeFileSync } from "node:fs";
import { fawkes } from "../pet/assets/src/index";
import { ALL_DISPLAY_STATES, STATE_VISUALS } from "../pet/states/src/index";

const COLS = 4;
const CELL = 120;
const ART = 80;

function gallery(still: boolean): string {
  const inner = fawkes.svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
  const cells = ALL_DISPLAY_STATES.map((state, i) => {
    const v = STATE_VISUALS[state];
    const x = (i % COLS) * CELL + (CELL - ART) / 2;
    const y = Math.floor(i / COLS) * (CELL + 20) + 10;
    const recording =
      state === "RECORDING"
        ? `<circle cx="${ART - 8}" cy="8" r="7" fill="#e03131" stroke="#fff" stroke-width="2"/>`
        : "";
    return `<g transform="translate(${x} ${y})">
  <g class="fawkes" data-animation="${v.animation}" data-reduced-motion="${still}">
    <g class="fawkes-svg" transform="scale(${ART / 64})">${inner}</g>
  </g>${recording}
  <text x="${ART / 2}" y="${ART + 22}" text-anchor="middle">${v.label}</text>
</g>`;
  }).join("\n");
  const rows = Math.ceil(ALL_DISPLAY_STATES.length / COLS);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${COLS * CELL} ${rows * (CELL + 20)}" width="${COLS * CELL}" height="${rows * (CELL + 20)}">
<title>Fawkes states${still ? " (reduced motion)" : ""}</title>
<!-- Fawkes artwork: CC BY-SA 4.0, Phoenix contributors (pet/assets). Generated by scripts/render-fawkes-gallery.ts. -->
<style>
text { font: 600 13px system-ui, -apple-system, sans-serif; fill: #868e96; }
${fawkes.css}
${still ? "* { animation: none !important; }" : ""}
</style>
${cells}
</svg>
`;
}

writeFileSync("docs/images/fawkes-states.svg", gallery(false));
writeFileSync("docs/images/fawkes-states-still.svg", gallery(true));
console.log("wrote docs/images/fawkes-states.svg and fawkes-states-still.svg");
